#!/bin/bash
{
    sleep 0.5
    echo -e "XXX\n0\nyum remove package_0... \nXXX"
    sleep 2
    echo -e "XXX\n25\nyum remove package_0... Done.\nXXX"
    sleep 0.5

    echo -e "XXX\n25\nyum remove package_1... \nXXX"
    sleep 2
    echo -e "XXX\n50\nyum remove package_1... Done.\nXXX"
    sleep 0.5

    echo -e "XXX\n50\nyum remove package_2... \nXXX"
    sleep 2
    echo -e "XXX\n75\nyum remove package_2... Done.\nXXX"
    sleep 0.5

    echo -e "XXX\n75\nyum remove package_3... \nXXX"
    sleep 2
    echo -e "XXX\n100\nyum remove package_3... Done.\nXXX"
    sleep 1
} |whiptail --title "Yum Removal" --gauge "Please wait while installing" 6 60 0

dialog example

counter=0
(
while :
do
cat <<EOF
XXX
$counter
git clone https://github.com/mdhiggins/sickbeard_mp4_automator.git mp4auto ( $counter%):
XXX
EOF
(( counter+=10 ))
[ $counter -eq 100 ] && break
sleep 1
done
) | dialog --title "Cloaning MP4Automator" --gauge "Please wait" 7 70 0
