#!/bin/bash
{
    sleep 0.5
    echo -e "XXX\n0\nyum remove package_0... \nXXX"
    sleep 2
    echo -e "XXX\n25\nyum remove package_0... Done.\nXXX"
    sleep 0.5

    echo -e "XXX\n25\nyum remove package_1... \nXXX"
    sleep 2
    echo -e "XXX\n50\nyum remove package_1... Done.\nXXX"
    sleep 0.5

    echo -e "XXX\n50\nyum remove package_2... \nXXX"
    sleep 2
    echo -e "XXX\n75\nyum remove package_2... Done.\nXXX"
    sleep 0.5

    echo -e "XXX\n75\nyum remove package_3... \nXXX"
    sleep 2
    echo -e "XXX\n100\nyum remove package_3... Done.\nXXX"
    sleep 1
} |whiptail --title "Yum Removal" --gauge "Please wait while installing" 6 60 0

dialog example

counter=0
(
while :
do
cat <<EOF
XXX
$counter
git clone https://github.com/mdhiggins/sickbeard_mp4_automator.git mp4auto ( $counter%):
XXX
EOF
(( counter+=10 ))
[ $counter -eq 100 ] && break
sleep 1
done
) | dialog --title "Cloaning MP4Automator" --gauge "Please wait" 7 70 0



BOOT_TIMEOUT=60
locale="en_CA"
keyboard=us
KERNEL_PARAMS="$KERNEL_PARAMS DEBIAN_FRONTEND=newt BOOT_DEBUG=1 fb=false vga=normal"
vga_normal="true"
dist="stable"
server="deb.debian.org"
security_mirror="http://security.debian.org/"
mirror_components="main non-free non-free-firmware"
#debian_mirror_extra="https://packages.sury.org/php/"
#mirror_components_extra="main"
export ARCH=${ARCH:-`dpkg --print-architecture`}
export ARCHES=$ARCH
export CONTRIB=1
export NONFREE=1
export MAXCDS=1
export SIZELIMIT=8000000000
export OMIT_MANUAL=1
export OMIT_DOC_TOOLS=1
backports=true
backports_packages="checkinstall"
simple_cdd_dir=$(pwd)
# export SPLASHPNG="$simple_cdd_dir/yourimage.png"
export DOJIGDO=0
export DISKINFO="Simple-cdd Installer: Debian GNU/Linux $DEBVERSION $CODENAME $(date --utc +%Y%m%d)"
